;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="EQS",DevComment="")
+GameplayTagList=(Tag="EQS.TargetManager",DevComment="")
+GameplayTagList=(Tag="EQS.TargetManager.Level",DevComment="")
+GameplayTagList=(Tag="EQS.TargetManager.Level.1",DevComment="")
+GameplayTagList=(Tag="EQS.TargetManager.Level.2",DevComment="")
+GameplayTagList=(Tag="EQS.TargetManager.Level.3",DevComment="")

